/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ClickSend.Api;

import ClickSend.ApiException;
import ClickSend.Model.ListOwnNumbers;
import ClickSend.Model.OwnNumber;
import ClickSend.Model.RequestOwnNumberVerificationOtp;
import ClickSend.Model.RequestOwnNumberVerificationOtpRequest;
import ClickSend.Model.VerifyOwnNumberOtp;
import ClickSend.Model.VerifyOwnNumberOtpRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OwnNumbersApi
 */
@Disabled
public class OwnNumbersApiTest {

    private final OwnNumbersApi api = new OwnNumbersApi();

    /**
     * Delete Own Number
     *
     * _Delete a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteOwnNumberTest() throws ApiException {
        String ownNumberId = null;
        String contentType = null;
        OwnNumber response = api.deleteOwnNumber(ownNumberId, contentType);
        // TODO: test validations
    }

    /**
     * Get Own Number Detail
     *
     * _Get a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOwnNumberDetailTest() throws ApiException {
        String ownNumberId = null;
        String contentType = null;
        OwnNumber response = api.getOwnNumberDetail(ownNumberId, contentType);
        // TODO: test validations
    }

    /**
     * List Own Numbers
     *
     * _List own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | offset | query | uuid | false | Page(offset) to be used for pagination. Example: &#x60;offset&#x3D;f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4#8fa5ebc2-777b-45db-a448-ec76a40d4384&#x60; | | page_size | query | integer | false | Number of records per page. Default: 10. Range \\[1..500\\] | | filter\\[status\\]\\[\\] | query | string | false | Filter by statuses. Value must be in enum \\[&#x60;PENDING&#x60;, &#x60;APPROVED&#x60;, &#x60;REJECTED&#x60;\\]. For example: &#x60;filter[status][0]&#x3D;PENDING&amp;filter[status][1]&#x3D;APPROVED&#x60; . | | sort_by | query | string | false | Sort by parameter. Default: &#x60;created_timestamp&#x60; | | sort_direction | query | string | false | Direction of sorting. Default: &#x60;asc&#x60;. Value must be in enum \\[&#x60;asc&#x60;, &#x60;desc&#x60;\\]. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listOwnNumbersTest() throws ApiException {
        String contentType = null;
        ListOwnNumbers response = api.listOwnNumbers(contentType);
        // TODO: test validations
    }

    /**
     * Request Own Number Verification OTP
     *
     * _Request to generate own number verification OTP_  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestOwnNumberVerificationOtpTest() throws ApiException {
        String contentType = null;
        RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest = null;
        RequestOwnNumberVerificationOtp response = api.requestOwnNumberVerificationOtp(contentType, requestOwnNumberVerificationOtpRequest);
        // TODO: test validations
    }

    /**
     * Update Own Number
     *
     * _Update details of a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateOwnNumberTest() throws ApiException {
        String ownNumberId = null;
        OwnNumber response = api.updateOwnNumber(ownNumberId);
        // TODO: test validations
    }

    /**
     * Verify Own Number OTP
     *
     * _Request to verify an OTP for Own Number verification_  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | verification_id | path | uuid | true | ID of the Own Number verification |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | code | string | true | none | OTP code. Length must be 6 characters | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyOwnNumberOtpTest() throws ApiException {
        String verificationId = null;
        String contentType = null;
        VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest = null;
        VerifyOwnNumberOtp response = api.verifyOwnNumberOtp(verificationId, contentType, verifyOwnNumberOtpRequest);
        // TODO: test validations
    }

}
