/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ClickSend.Model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ViewAllowedEmailsDataAllOfDataInner
 */
public class ViewAllowedEmailsDataAllOfDataInnerTest {
    private final ViewAllowedEmailsDataAllOfDataInner model = new ViewAllowedEmailsDataAllOfDataInner();

    /**
     * Model tests for ViewAllowedEmailsDataAllOfDataInner
     */
    @Test
    public void testViewAllowedEmailsDataAllOfDataInner() {
        // TODO: test ViewAllowedEmailsDataAllOfDataInner
    }

    /**
     * Test the property 'emailAddressId'
     */
    @Test
    public void emailAddressIdTest() {
        // TODO: test emailAddressId
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'subaccountId'
     */
    @Test
    public void subaccountIdTest() {
        // TODO: test subaccountId
    }

    /**
     * Test the property 'fromFax'
     */
    @Test
    public void fromFaxTest() {
        // TODO: test fromFax
    }

    /**
     * Test the property 'voice'
     */
    @Test
    public void voiceTest() {
        // TODO: test voice
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'subaccountName'
     */
    @Test
    public void subaccountNameTest() {
        // TODO: test subaccountName
    }

}
