/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NumberApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public NumberApi() {
        this(Configuration.getDefaultApiClient());
    }

    public NumberApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for numbersBuyByDedicatedNumberPost
     * @param dedicatedNumber Phone number to purchase (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersBuyByDedicatedNumberPostCall(@javax.annotation.Nonnull String dedicatedNumber, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/numbers/buy/{dedicated_number}"
            .replace("{" + "dedicated_number" + "}", localVarApiClient.escapeString(dedicatedNumber.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BasicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call numbersBuyByDedicatedNumberPostValidateBeforeCall(@javax.annotation.Nonnull String dedicatedNumber, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'dedicatedNumber' is set
        if (dedicatedNumber == null) {
            throw new ApiException("Missing the required parameter 'dedicatedNumber' when calling numbersBuyByDedicatedNumberPost(Async)");
        }

        return numbersBuyByDedicatedNumberPostCall(dedicatedNumber, _callback);

    }

    /**
     * Buy dedicated number
     * Buy dedicated number
     * @param dedicatedNumber Phone number to purchase (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public String numbersBuyByDedicatedNumberPost(@javax.annotation.Nonnull String dedicatedNumber) throws ApiException {
        ApiResponse<String> localVarResp = numbersBuyByDedicatedNumberPostWithHttpInfo(dedicatedNumber);
        return localVarResp.getData();
    }

    /**
     * Buy dedicated number
     * Buy dedicated number
     * @param dedicatedNumber Phone number to purchase (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> numbersBuyByDedicatedNumberPostWithHttpInfo(@javax.annotation.Nonnull String dedicatedNumber) throws ApiException {
        okhttp3.Call localVarCall = numbersBuyByDedicatedNumberPostValidateBeforeCall(dedicatedNumber, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buy dedicated number (asynchronously)
     * Buy dedicated number
     * @param dedicatedNumber Phone number to purchase (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersBuyByDedicatedNumberPostAsync(@javax.annotation.Nonnull String dedicatedNumber, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = numbersBuyByDedicatedNumberPostValidateBeforeCall(dedicatedNumber, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for numbersGet
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersGetCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/numbers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BasicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call numbersGetValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        return numbersGetCall(page, limit, _callback);

    }

    /**
     * Get all availible dedicated numbers
     * Get all availible dedicated numbers
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public String numbersGet(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<String> localVarResp = numbersGetWithHttpInfo(page, limit);
        return localVarResp.getData();
    }

    /**
     * Get all availible dedicated numbers
     * Get all availible dedicated numbers
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> numbersGetWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = numbersGetValidateBeforeCall(page, limit, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all availible dedicated numbers (asynchronously)
     * Get all availible dedicated numbers
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersGetAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = numbersGetValidateBeforeCall(page, limit, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for numbersSearchByCountryGet
     * @param country Country code to search (required)
     * @param search Your search pattern or query. (optional)
     * @param searchType Your strategy for searching, 0 &#x3D; starts with, 1 &#x3D; anywhere, 2 &#x3D; ends with. (optional)
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersSearchByCountryGetCall(@javax.annotation.Nonnull String country, @javax.annotation.Nullable String search, @javax.annotation.Nullable Integer searchType, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/numbers/search/{country}"
            .replace("{" + "country" + "}", localVarApiClient.escapeString(country.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        if (searchType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search_type", searchType));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BasicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call numbersSearchByCountryGetValidateBeforeCall(@javax.annotation.Nonnull String country, @javax.annotation.Nullable String search, @javax.annotation.Nullable Integer searchType, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'country' is set
        if (country == null) {
            throw new ApiException("Missing the required parameter 'country' when calling numbersSearchByCountryGet(Async)");
        }

        return numbersSearchByCountryGetCall(country, search, searchType, page, limit, _callback);

    }

    /**
     * Get all dedicated numbers by country
     * Get all dedicated numbers by country
     * @param country Country code to search (required)
     * @param search Your search pattern or query. (optional)
     * @param searchType Your strategy for searching, 0 &#x3D; starts with, 1 &#x3D; anywhere, 2 &#x3D; ends with. (optional)
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public String numbersSearchByCountryGet(@javax.annotation.Nonnull String country, @javax.annotation.Nullable String search, @javax.annotation.Nullable Integer searchType, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<String> localVarResp = numbersSearchByCountryGetWithHttpInfo(country, search, searchType, page, limit);
        return localVarResp.getData();
    }

    /**
     * Get all dedicated numbers by country
     * Get all dedicated numbers by country
     * @param country Country code to search (required)
     * @param search Your search pattern or query. (optional)
     * @param searchType Your strategy for searching, 0 &#x3D; starts with, 1 &#x3D; anywhere, 2 &#x3D; ends with. (optional)
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> numbersSearchByCountryGetWithHttpInfo(@javax.annotation.Nonnull String country, @javax.annotation.Nullable String search, @javax.annotation.Nullable Integer searchType, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = numbersSearchByCountryGetValidateBeforeCall(country, search, searchType, page, limit, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all dedicated numbers by country (asynchronously)
     * Get all dedicated numbers by country
     * @param country Country code to search (required)
     * @param search Your search pattern or query. (optional)
     * @param searchType Your strategy for searching, 0 &#x3D; starts with, 1 &#x3D; anywhere, 2 &#x3D; ends with. (optional)
     * @param page Page number (optional, default to 1)
     * @param limit Number of records per page (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> SUCCESS </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> BAD_REQUEST </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> FORBIDDEN </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> METHOD_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> INTERNAL_SERVER_ERROR </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call numbersSearchByCountryGetAsync(@javax.annotation.Nonnull String country, @javax.annotation.Nullable String search, @javax.annotation.Nullable Integer searchType, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = numbersSearchByCountryGetValidateBeforeCall(country, search, searchType, page, limit, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
