/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ListOwnNumbers;
import org.openapitools.client.model.OwnNumber;
import org.openapitools.client.model.RequestOwnNumberVerificationOtp;
import org.openapitools.client.model.RequestOwnNumberVerificationOtpRequest;
import org.openapitools.client.model.VerifyOwnNumberOtp;
import org.openapitools.client.model.VerifyOwnNumberOtpRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OwnNumbersOtherApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OwnNumbersOtherApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OwnNumbersOtherApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteOwnNumber
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOwnNumberCall(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v3/own-numbers/{own_number_id}"
            .replace("{" + "own_number_id" + "}", localVarApiClient.escapeString(ownNumberId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteOwnNumberValidateBeforeCall(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ownNumberId' is set
        if (ownNumberId == null) {
            throw new ApiException("Missing the required parameter 'ownNumberId' when calling deleteOwnNumber(Async)");
        }

        return deleteOwnNumberCall(ownNumberId, contentType, _callback);

    }

    /**
     * Delete Own Number
     * _Delete a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @return OwnNumber
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public OwnNumber deleteOwnNumber(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType) throws ApiException {
        ApiResponse<OwnNumber> localVarResp = deleteOwnNumberWithHttpInfo(ownNumberId, contentType);
        return localVarResp.getData();
    }

    /**
     * Delete Own Number
     * _Delete a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @return ApiResponse&lt;OwnNumber&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OwnNumber> deleteOwnNumberWithHttpInfo(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = deleteOwnNumberValidateBeforeCall(ownNumberId, contentType, null);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Own Number (asynchronously)
     * _Delete a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOwnNumberAsync(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback<OwnNumber> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteOwnNumberValidateBeforeCall(ownNumberId, contentType, _callback);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getOwnNumberDetail
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOwnNumberDetailCall(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v3/own-numbers/{own_number_id}"
            .replace("{" + "own_number_id" + "}", localVarApiClient.escapeString(ownNumberId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOwnNumberDetailValidateBeforeCall(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ownNumberId' is set
        if (ownNumberId == null) {
            throw new ApiException("Missing the required parameter 'ownNumberId' when calling getOwnNumberDetail(Async)");
        }

        return getOwnNumberDetailCall(ownNumberId, contentType, _callback);

    }

    /**
     * Get Own Number Detail
     * _Get a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @return OwnNumber
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public OwnNumber getOwnNumberDetail(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType) throws ApiException {
        ApiResponse<OwnNumber> localVarResp = getOwnNumberDetailWithHttpInfo(ownNumberId, contentType);
        return localVarResp.getData();
    }

    /**
     * Get Own Number Detail
     * _Get a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @return ApiResponse&lt;OwnNumber&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OwnNumber> getOwnNumberDetailWithHttpInfo(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = getOwnNumberDetailValidateBeforeCall(ownNumberId, contentType, null);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Own Number Detail (asynchronously)
     * _Get a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOwnNumberDetailAsync(@javax.annotation.Nonnull String ownNumberId, @javax.annotation.Nullable String contentType, final ApiCallback<OwnNumber> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOwnNumberDetailValidateBeforeCall(ownNumberId, contentType, _callback);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listOwnNumbers
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listOwnNumbersCall(@javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v3/own-numbers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listOwnNumbersValidateBeforeCall(@javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        return listOwnNumbersCall(contentType, _callback);

    }

    /**
     * List Own Numbers
     * _List own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | offset | query | uuid | false | Page(offset) to be used for pagination. Example: &#x60;offset&#x3D;f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4#8fa5ebc2-777b-45db-a448-ec76a40d4384&#x60; | | page_size | query | integer | false | Number of records per page. Default: 10. Range \\[1..500\\] | | filter\\[status\\]\\[\\] | query | string | false | Filter by statuses. Value must be in enum \\[&#x60;PENDING&#x60;, &#x60;APPROVED&#x60;, &#x60;REJECTED&#x60;\\]. For example: &#x60;filter[status][0]&#x3D;PENDING&amp;filter[status][1]&#x3D;APPROVED&#x60; . | | sort_by | query | string | false | Sort by parameter. Default: &#x60;created_timestamp&#x60; | | sort_direction | query | string | false | Direction of sorting. Default: &#x60;asc&#x60;. Value must be in enum \\[&#x60;asc&#x60;, &#x60;desc&#x60;\\]. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @return ListOwnNumbers
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ListOwnNumbers listOwnNumbers(@javax.annotation.Nullable String contentType) throws ApiException {
        ApiResponse<ListOwnNumbers> localVarResp = listOwnNumbersWithHttpInfo(contentType);
        return localVarResp.getData();
    }

    /**
     * List Own Numbers
     * _List own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | offset | query | uuid | false | Page(offset) to be used for pagination. Example: &#x60;offset&#x3D;f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4#8fa5ebc2-777b-45db-a448-ec76a40d4384&#x60; | | page_size | query | integer | false | Number of records per page. Default: 10. Range \\[1..500\\] | | filter\\[status\\]\\[\\] | query | string | false | Filter by statuses. Value must be in enum \\[&#x60;PENDING&#x60;, &#x60;APPROVED&#x60;, &#x60;REJECTED&#x60;\\]. For example: &#x60;filter[status][0]&#x3D;PENDING&amp;filter[status][1]&#x3D;APPROVED&#x60; . | | sort_by | query | string | false | Sort by parameter. Default: &#x60;created_timestamp&#x60; | | sort_direction | query | string | false | Direction of sorting. Default: &#x60;asc&#x60;. Value must be in enum \\[&#x60;asc&#x60;, &#x60;desc&#x60;\\]. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @return ApiResponse&lt;ListOwnNumbers&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListOwnNumbers> listOwnNumbersWithHttpInfo(@javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = listOwnNumbersValidateBeforeCall(contentType, null);
        Type localVarReturnType = new TypeToken<ListOwnNumbers>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Own Numbers (asynchronously)
     * _List own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | offset | query | uuid | false | Page(offset) to be used for pagination. Example: &#x60;offset&#x3D;f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4#8fa5ebc2-777b-45db-a448-ec76a40d4384&#x60; | | page_size | query | integer | false | Number of records per page. Default: 10. Range \\[1..500\\] | | filter\\[status\\]\\[\\] | query | string | false | Filter by statuses. Value must be in enum \\[&#x60;PENDING&#x60;, &#x60;APPROVED&#x60;, &#x60;REJECTED&#x60;\\]. For example: &#x60;filter[status][0]&#x3D;PENDING&amp;filter[status][1]&#x3D;APPROVED&#x60; . | | sort_by | query | string | false | Sort by parameter. Default: &#x60;created_timestamp&#x60; | | sort_direction | query | string | false | Direction of sorting. Default: &#x60;asc&#x60;. Value must be in enum \\[&#x60;asc&#x60;, &#x60;desc&#x60;\\]. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listOwnNumbersAsync(@javax.annotation.Nullable String contentType, final ApiCallback<ListOwnNumbers> _callback) throws ApiException {

        okhttp3.Call localVarCall = listOwnNumbersValidateBeforeCall(contentType, _callback);
        Type localVarReturnType = new TypeToken<ListOwnNumbers>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for requestOwnNumberVerificationOtp
     * @param contentType  (optional)
     * @param requestOwnNumberVerificationOtpRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call requestOwnNumberVerificationOtpCall(@javax.annotation.Nullable String contentType, @javax.annotation.Nullable RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestOwnNumberVerificationOtpRequest;

        // create path and map variables
        String localVarPath = "/v3/own-numbers/verifications";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call requestOwnNumberVerificationOtpValidateBeforeCall(@javax.annotation.Nullable String contentType, @javax.annotation.Nullable RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest, final ApiCallback _callback) throws ApiException {
        return requestOwnNumberVerificationOtpCall(contentType, requestOwnNumberVerificationOtpRequest, _callback);

    }

    /**
     * Request Own Number Verification OTP
     * _Request to generate own number verification OTP_  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @param requestOwnNumberVerificationOtpRequest  (optional)
     * @return RequestOwnNumberVerificationOtp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public RequestOwnNumberVerificationOtp requestOwnNumberVerificationOtp(@javax.annotation.Nullable String contentType, @javax.annotation.Nullable RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest) throws ApiException {
        ApiResponse<RequestOwnNumberVerificationOtp> localVarResp = requestOwnNumberVerificationOtpWithHttpInfo(contentType, requestOwnNumberVerificationOtpRequest);
        return localVarResp.getData();
    }

    /**
     * Request Own Number Verification OTP
     * _Request to generate own number verification OTP_  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @param requestOwnNumberVerificationOtpRequest  (optional)
     * @return ApiResponse&lt;RequestOwnNumberVerificationOtp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RequestOwnNumberVerificationOtp> requestOwnNumberVerificationOtpWithHttpInfo(@javax.annotation.Nullable String contentType, @javax.annotation.Nullable RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest) throws ApiException {
        okhttp3.Call localVarCall = requestOwnNumberVerificationOtpValidateBeforeCall(contentType, requestOwnNumberVerificationOtpRequest, null);
        Type localVarReturnType = new TypeToken<RequestOwnNumberVerificationOtp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Request Own Number Verification OTP (asynchronously)
     * _Request to generate own number verification OTP_  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param contentType  (optional)
     * @param requestOwnNumberVerificationOtpRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call requestOwnNumberVerificationOtpAsync(@javax.annotation.Nullable String contentType, @javax.annotation.Nullable RequestOwnNumberVerificationOtpRequest requestOwnNumberVerificationOtpRequest, final ApiCallback<RequestOwnNumberVerificationOtp> _callback) throws ApiException {

        okhttp3.Call localVarCall = requestOwnNumberVerificationOtpValidateBeforeCall(contentType, requestOwnNumberVerificationOtpRequest, _callback);
        Type localVarReturnType = new TypeToken<RequestOwnNumberVerificationOtp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateOwnNumber
     * @param ownNumberId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOwnNumberCall(@javax.annotation.Nonnull String ownNumberId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v3/own-numbers/{own_number_id}"
            .replace("{" + "own_number_id" + "}", localVarApiClient.escapeString(ownNumberId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateOwnNumberValidateBeforeCall(@javax.annotation.Nonnull String ownNumberId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ownNumberId' is set
        if (ownNumberId == null) {
            throw new ApiException("Missing the required parameter 'ownNumberId' when calling updateOwnNumber(Async)");
        }

        return updateOwnNumberCall(ownNumberId, _callback);

    }

    /**
     * Update Own Number
     * _Update details of a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @return OwnNumber
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public OwnNumber updateOwnNumber(@javax.annotation.Nonnull String ownNumberId) throws ApiException {
        ApiResponse<OwnNumber> localVarResp = updateOwnNumberWithHttpInfo(ownNumberId);
        return localVarResp.getData();
    }

    /**
     * Update Own Number
     * _Update details of a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @return ApiResponse&lt;OwnNumber&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OwnNumber> updateOwnNumberWithHttpInfo(@javax.annotation.Nonnull String ownNumberId) throws ApiException {
        okhttp3.Call localVarCall = updateOwnNumberValidateBeforeCall(ownNumberId, null);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Own Number (asynchronously)
     * _Update details of a specific own numbers._  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | own_number_id | path | uuid | true | ID of the own number |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | label | string | false | none | Custom label for phone number. Length must be between 1 - 200 characters. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param ownNumberId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOwnNumberAsync(@javax.annotation.Nonnull String ownNumberId, final ApiCallback<OwnNumber> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateOwnNumberValidateBeforeCall(ownNumberId, _callback);
        Type localVarReturnType = new TypeToken<OwnNumber>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for verifyOwnNumberOtp
     * @param verificationId  (required)
     * @param contentType  (optional)
     * @param verifyOwnNumberOtpRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyOwnNumberOtpCall(@javax.annotation.Nonnull String verificationId, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = verifyOwnNumberOtpRequest;

        // create path and map variables
        String localVarPath = "/v3/own-numbers/verifications/{verification_id}/verify"
            .replace("{" + "verification_id" + "}", localVarApiClient.escapeString(verificationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifyOwnNumberOtpValidateBeforeCall(@javax.annotation.Nonnull String verificationId, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'verificationId' is set
        if (verificationId == null) {
            throw new ApiException("Missing the required parameter 'verificationId' when calling verifyOwnNumberOtp(Async)");
        }

        return verifyOwnNumberOtpCall(verificationId, contentType, verifyOwnNumberOtpRequest, _callback);

    }

    /**
     * Verify Own Number OTP
     * _Request to verify an OTP for Own Number verification_  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | verification_id | path | uuid | true | ID of the Own Number verification |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | code | string | true | none | OTP code. Length must be 6 characters | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param verificationId  (required)
     * @param contentType  (optional)
     * @param verifyOwnNumberOtpRequest  (optional)
     * @return VerifyOwnNumberOtp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public VerifyOwnNumberOtp verifyOwnNumberOtp(@javax.annotation.Nonnull String verificationId, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest) throws ApiException {
        ApiResponse<VerifyOwnNumberOtp> localVarResp = verifyOwnNumberOtpWithHttpInfo(verificationId, contentType, verifyOwnNumberOtpRequest);
        return localVarResp.getData();
    }

    /**
     * Verify Own Number OTP
     * _Request to verify an OTP for Own Number verification_  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | verification_id | path | uuid | true | ID of the Own Number verification |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | code | string | true | none | OTP code. Length must be 6 characters | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param verificationId  (required)
     * @param contentType  (optional)
     * @param verifyOwnNumberOtpRequest  (optional)
     * @return ApiResponse&lt;VerifyOwnNumberOtp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VerifyOwnNumberOtp> verifyOwnNumberOtpWithHttpInfo(@javax.annotation.Nonnull String verificationId, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest) throws ApiException {
        okhttp3.Call localVarCall = verifyOwnNumberOtpValidateBeforeCall(verificationId, contentType, verifyOwnNumberOtpRequest, null);
        Type localVarReturnType = new TypeToken<VerifyOwnNumberOtp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Verify Own Number OTP (asynchronously)
     * _Request to verify an OTP for Own Number verification_  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | verification_id | path | uuid | true | ID of the Own Number verification |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | code | string | true | none | OTP code. Length must be 6 characters | | phone_number | string | true | none | Phone number. | | country | string | false | none | Country code. |  Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.  This endpoint requires authentication, [more info...](/#authentication)
     * @param verificationId  (required)
     * @param contentType  (optional)
     * @param verifyOwnNumberOtpRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyOwnNumberOtpAsync(@javax.annotation.Nonnull String verificationId, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable VerifyOwnNumberOtpRequest verifyOwnNumberOtpRequest, final ApiCallback<VerifyOwnNumberOtp> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifyOwnNumberOtpValidateBeforeCall(verificationId, contentType, verifyOwnNumberOtpRequest, _callback);
        Type localVarReturnType = new TypeToken<VerifyOwnNumberOtp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
