/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Subaccount
 */
public class SubaccountTest {
    private final Subaccount model = new Subaccount();

    /**
     * Model tests for Subaccount
     */
    @Test
    public void testSubaccount() {
        // TODO: test Subaccount
    }

    /**
     * Test the property 'apiUsername'
     */
    @Test
    public void apiUsernameTest() {
        // TODO: test apiUsername
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'accessUsers'
     */
    @Test
    public void accessUsersTest() {
        // TODO: test accessUsers
    }

    /**
     * Test the property 'accessBilling'
     */
    @Test
    public void accessBillingTest() {
        // TODO: test accessBilling
    }

    /**
     * Test the property 'accessReporting'
     */
    @Test
    public void accessReportingTest() {
        // TODO: test accessReporting
    }

    /**
     * Test the property 'accessContacts'
     */
    @Test
    public void accessContactsTest() {
        // TODO: test accessContacts
    }

    /**
     * Test the property 'accessSettings'
     */
    @Test
    public void accessSettingsTest() {
        // TODO: test accessSettings
    }

}
