/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ClickSend.Model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ClickSend.JSON;

/**
 * Contact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class Contact {
  public static final String SERIALIZED_NAME_CONTACT_ID = "contact_id";
  @SerializedName(SERIALIZED_NAME_CONTACT_ID)
  @javax.annotation.Nullable
  private Integer contactId;

  public static final String SERIALIZED_NAME_LIST_ID = "list_id";
  @SerializedName(SERIALIZED_NAME_LIST_ID)
  @javax.annotation.Nullable
  private Integer listId;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phone_number";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  @javax.annotation.Nullable
  private String phoneNumber;

  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @javax.annotation.Nullable
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  @javax.annotation.Nullable
  private String lastName;

  public static final String SERIALIZED_NAME_CUSTOM1 = "custom_1";
  @SerializedName(SERIALIZED_NAME_CUSTOM1)
  @javax.annotation.Nullable
  private String custom1;

  public static final String SERIALIZED_NAME_CUSTOM2 = "custom_2";
  @SerializedName(SERIALIZED_NAME_CUSTOM2)
  @javax.annotation.Nullable
  private String custom2;

  public static final String SERIALIZED_NAME_CUSTOM3 = "custom_3";
  @SerializedName(SERIALIZED_NAME_CUSTOM3)
  @javax.annotation.Nullable
  private String custom3;

  public static final String SERIALIZED_NAME_CUSTOM4 = "custom_4";
  @SerializedName(SERIALIZED_NAME_CUSTOM4)
  @javax.annotation.Nullable
  private String custom4;

  public static final String SERIALIZED_NAME_DATE_ADDED = "date_added";
  @SerializedName(SERIALIZED_NAME_DATE_ADDED)
  @javax.annotation.Nullable
  private Integer dateAdded;

  public static final String SERIALIZED_NAME_DATE_UPDATED = "date_updated";
  @SerializedName(SERIALIZED_NAME_DATE_UPDATED)
  @javax.annotation.Nullable
  private Integer dateUpdated;

  public static final String SERIALIZED_NAME_FAX_NUMBER = "fax_number";
  @SerializedName(SERIALIZED_NAME_FAX_NUMBER)
  @javax.annotation.Nullable
  private String faxNumber;

  public static final String SERIALIZED_NAME_ORGANIZATION_NAME = "organization_name";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_NAME)
  @javax.annotation.Nullable
  private String organizationName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "address_line_1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  @javax.annotation.Nullable
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "address_line_2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  @javax.annotation.Nullable
  private String addressLine2;

  public static final String SERIALIZED_NAME_ADDRESS_CITY = "address_city";
  @SerializedName(SERIALIZED_NAME_ADDRESS_CITY)
  @javax.annotation.Nullable
  private String addressCity;

  public static final String SERIALIZED_NAME_ADDRESS_STATE = "address_state";
  @SerializedName(SERIALIZED_NAME_ADDRESS_STATE)
  @javax.annotation.Nullable
  private String addressState;

  public static final String SERIALIZED_NAME_ADDRESS_POSTAL_CODE = "address_postal_code";
  @SerializedName(SERIALIZED_NAME_ADDRESS_POSTAL_CODE)
  @javax.annotation.Nullable
  private String addressPostalCode;

  public static final String SERIALIZED_NAME_ADDRESS_COUNTRY = "address_country";
  @SerializedName(SERIALIZED_NAME_ADDRESS_COUNTRY)
  @javax.annotation.Nullable
  private String addressCountry;

  public static final String SERIALIZED_NAME_LIST_NAME = "_list_name";
  @SerializedName(SERIALIZED_NAME_LIST_NAME)
  @javax.annotation.Nullable
  private String listName;

  public Contact() {
  }

  public Contact contactId(@javax.annotation.Nullable Integer contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * The unique identifier for the contact.
   * @return contactId
   */
  @javax.annotation.Nullable
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(@javax.annotation.Nullable Integer contactId) {
    this.contactId = contactId;
  }


  public Contact listId(@javax.annotation.Nullable Integer listId) {
    this.listId = listId;
    return this;
  }

  /**
   * The identifier of the list the contact belongs to.
   * @return listId
   */
  @javax.annotation.Nullable
  public Integer getListId() {
    return listId;
  }

  public void setListId(@javax.annotation.Nullable Integer listId) {
    this.listId = listId;
  }


  public Contact phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * The phone number of the contact.
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public Contact firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * The first name of the contact.
   * @return firstName
   */
  @javax.annotation.Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public Contact lastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * The last name of the contact.
   * @return lastName
   */
  @javax.annotation.Nullable
  public String getLastName() {
    return lastName;
  }

  public void setLastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  public Contact custom1(@javax.annotation.Nullable String custom1) {
    this.custom1 = custom1;
    return this;
  }

  /**
   * Custom field 1.
   * @return custom1
   */
  @javax.annotation.Nullable
  public String getCustom1() {
    return custom1;
  }

  public void setCustom1(@javax.annotation.Nullable String custom1) {
    this.custom1 = custom1;
  }


  public Contact custom2(@javax.annotation.Nullable String custom2) {
    this.custom2 = custom2;
    return this;
  }

  /**
   * Custom field 2.
   * @return custom2
   */
  @javax.annotation.Nullable
  public String getCustom2() {
    return custom2;
  }

  public void setCustom2(@javax.annotation.Nullable String custom2) {
    this.custom2 = custom2;
  }


  public Contact custom3(@javax.annotation.Nullable String custom3) {
    this.custom3 = custom3;
    return this;
  }

  /**
   * Custom field 3.
   * @return custom3
   */
  @javax.annotation.Nullable
  public String getCustom3() {
    return custom3;
  }

  public void setCustom3(@javax.annotation.Nullable String custom3) {
    this.custom3 = custom3;
  }


  public Contact custom4(@javax.annotation.Nullable String custom4) {
    this.custom4 = custom4;
    return this;
  }

  /**
   * Custom field 4.
   * @return custom4
   */
  @javax.annotation.Nullable
  public String getCustom4() {
    return custom4;
  }

  public void setCustom4(@javax.annotation.Nullable String custom4) {
    this.custom4 = custom4;
  }


  public Contact dateAdded(@javax.annotation.Nullable Integer dateAdded) {
    this.dateAdded = dateAdded;
    return this;
  }

  /**
   * The date when the contact was added, as a &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix timestamp&lt;/a&gt;.
   * @return dateAdded
   */
  @javax.annotation.Nullable
  public Integer getDateAdded() {
    return dateAdded;
  }

  public void setDateAdded(@javax.annotation.Nullable Integer dateAdded) {
    this.dateAdded = dateAdded;
  }


  public Contact dateUpdated(@javax.annotation.Nullable Integer dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * The date when the contact was last updated, as a &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix timestamp&lt;/a&gt;.
   * @return dateUpdated
   */
  @javax.annotation.Nullable
  public Integer getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(@javax.annotation.Nullable Integer dateUpdated) {
    this.dateUpdated = dateUpdated;
  }


  public Contact faxNumber(@javax.annotation.Nullable String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

  /**
   * The fax number of the contact.
   * @return faxNumber
   */
  @javax.annotation.Nullable
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(@javax.annotation.Nullable String faxNumber) {
    this.faxNumber = faxNumber;
  }


  public Contact organizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * The organization name of the contact.
   * @return organizationName
   */
  @javax.annotation.Nullable
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
  }


  public Contact email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * The email address of the contact.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Contact addressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * The address line 1 of the contact.
   * @return addressLine1
   */
  @javax.annotation.Nullable
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public Contact addressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * The address line 2 of the contact.
   * @return addressLine2
   */
  @javax.annotation.Nullable
  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public Contact addressCity(@javax.annotation.Nullable String addressCity) {
    this.addressCity = addressCity;
    return this;
  }

  /**
   * The address city of the contact.
   * @return addressCity
   */
  @javax.annotation.Nullable
  public String getAddressCity() {
    return addressCity;
  }

  public void setAddressCity(@javax.annotation.Nullable String addressCity) {
    this.addressCity = addressCity;
  }


  public Contact addressState(@javax.annotation.Nullable String addressState) {
    this.addressState = addressState;
    return this;
  }

  /**
   * The address state of the contact.
   * @return addressState
   */
  @javax.annotation.Nullable
  public String getAddressState() {
    return addressState;
  }

  public void setAddressState(@javax.annotation.Nullable String addressState) {
    this.addressState = addressState;
  }


  public Contact addressPostalCode(@javax.annotation.Nullable String addressPostalCode) {
    this.addressPostalCode = addressPostalCode;
    return this;
  }

  /**
   * The address postal code of the contact.
   * @return addressPostalCode
   */
  @javax.annotation.Nullable
  public String getAddressPostalCode() {
    return addressPostalCode;
  }

  public void setAddressPostalCode(@javax.annotation.Nullable String addressPostalCode) {
    this.addressPostalCode = addressPostalCode;
  }


  public Contact addressCountry(@javax.annotation.Nullable String addressCountry) {
    this.addressCountry = addressCountry;
    return this;
  }

  /**
   * The address country of the contact.
   * @return addressCountry
   */
  @javax.annotation.Nullable
  public String getAddressCountry() {
    return addressCountry;
  }

  public void setAddressCountry(@javax.annotation.Nullable String addressCountry) {
    this.addressCountry = addressCountry;
  }


  public Contact listName(@javax.annotation.Nullable String listName) {
    this.listName = listName;
    return this;
  }

  /**
   * The name of the list the contact belongs to.
   * @return listName
   */
  @javax.annotation.Nullable
  public String getListName() {
    return listName;
  }

  public void setListName(@javax.annotation.Nullable String listName) {
    this.listName = listName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contact contact = (Contact) o;
    return Objects.equals(this.contactId, contact.contactId) &&
        Objects.equals(this.listId, contact.listId) &&
        Objects.equals(this.phoneNumber, contact.phoneNumber) &&
        Objects.equals(this.firstName, contact.firstName) &&
        Objects.equals(this.lastName, contact.lastName) &&
        Objects.equals(this.custom1, contact.custom1) &&
        Objects.equals(this.custom2, contact.custom2) &&
        Objects.equals(this.custom3, contact.custom3) &&
        Objects.equals(this.custom4, contact.custom4) &&
        Objects.equals(this.dateAdded, contact.dateAdded) &&
        Objects.equals(this.dateUpdated, contact.dateUpdated) &&
        Objects.equals(this.faxNumber, contact.faxNumber) &&
        Objects.equals(this.organizationName, contact.organizationName) &&
        Objects.equals(this.email, contact.email) &&
        Objects.equals(this.addressLine1, contact.addressLine1) &&
        Objects.equals(this.addressLine2, contact.addressLine2) &&
        Objects.equals(this.addressCity, contact.addressCity) &&
        Objects.equals(this.addressState, contact.addressState) &&
        Objects.equals(this.addressPostalCode, contact.addressPostalCode) &&
        Objects.equals(this.addressCountry, contact.addressCountry) &&
        Objects.equals(this.listName, contact.listName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactId, listId, phoneNumber, firstName, lastName, custom1, custom2, custom3, custom4, dateAdded, dateUpdated, faxNumber, organizationName, email, addressLine1, addressLine2, addressCity, addressState, addressPostalCode, addressCountry, listName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contact {\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    custom1: ").append(toIndentedString(custom1)).append("\n");
    sb.append("    custom2: ").append(toIndentedString(custom2)).append("\n");
    sb.append("    custom3: ").append(toIndentedString(custom3)).append("\n");
    sb.append("    custom4: ").append(toIndentedString(custom4)).append("\n");
    sb.append("    dateAdded: ").append(toIndentedString(dateAdded)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    addressCity: ").append(toIndentedString(addressCity)).append("\n");
    sb.append("    addressState: ").append(toIndentedString(addressState)).append("\n");
    sb.append("    addressPostalCode: ").append(toIndentedString(addressPostalCode)).append("\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("    listName: ").append(toIndentedString(listName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contact_id", "list_id", "phone_number", "first_name", "last_name", "custom_1", "custom_2", "custom_3", "custom_4", "date_added", "date_updated", "fax_number", "organization_name", "email", "address_line_1", "address_line_2", "address_city", "address_state", "address_postal_code", "address_country", "_list_name"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Contact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Contact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Contact is not found in the empty JSON string", Contact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Contact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Contact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("phone_number") != null && !jsonObj.get("phone_number").isJsonNull()) && !jsonObj.get("phone_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `phone_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone_number").toString()));
      }
      if ((jsonObj.get("first_name") != null && !jsonObj.get("first_name").isJsonNull()) && !jsonObj.get("first_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `first_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("first_name").toString()));
      }
      if ((jsonObj.get("last_name") != null && !jsonObj.get("last_name").isJsonNull()) && !jsonObj.get("last_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `last_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_name").toString()));
      }
      if ((jsonObj.get("custom_1") != null && !jsonObj.get("custom_1").isJsonNull()) && !jsonObj.get("custom_1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custom_1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_1").toString()));
      }
      if ((jsonObj.get("custom_2") != null && !jsonObj.get("custom_2").isJsonNull()) && !jsonObj.get("custom_2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custom_2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_2").toString()));
      }
      if ((jsonObj.get("custom_3") != null && !jsonObj.get("custom_3").isJsonNull()) && !jsonObj.get("custom_3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custom_3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_3").toString()));
      }
      if ((jsonObj.get("custom_4") != null && !jsonObj.get("custom_4").isJsonNull()) && !jsonObj.get("custom_4").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custom_4` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_4").toString()));
      }
      if ((jsonObj.get("fax_number") != null && !jsonObj.get("fax_number").isJsonNull()) && !jsonObj.get("fax_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fax_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fax_number").toString()));
      }
      if ((jsonObj.get("organization_name") != null && !jsonObj.get("organization_name").isJsonNull()) && !jsonObj.get("organization_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `organization_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_name").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("address_line_1") != null && !jsonObj.get("address_line_1").isJsonNull()) && !jsonObj.get("address_line_1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_line_1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_line_1").toString()));
      }
      if ((jsonObj.get("address_line_2") != null && !jsonObj.get("address_line_2").isJsonNull()) && !jsonObj.get("address_line_2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_line_2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_line_2").toString()));
      }
      if ((jsonObj.get("address_city") != null && !jsonObj.get("address_city").isJsonNull()) && !jsonObj.get("address_city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_city").toString()));
      }
      if ((jsonObj.get("address_state") != null && !jsonObj.get("address_state").isJsonNull()) && !jsonObj.get("address_state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_state").toString()));
      }
      if ((jsonObj.get("address_postal_code") != null && !jsonObj.get("address_postal_code").isJsonNull()) && !jsonObj.get("address_postal_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_postal_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_postal_code").toString()));
      }
      if ((jsonObj.get("address_country") != null && !jsonObj.get("address_country").isJsonNull()) && !jsonObj.get("address_country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `address_country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address_country").toString()));
      }
      if ((jsonObj.get("_list_name") != null && !jsonObj.get("_list_name").isJsonNull()) && !jsonObj.get("_list_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `_list_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_list_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Contact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Contact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Contact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Contact.class));

       return (TypeAdapter<T>) new TypeAdapter<Contact>() {
           @Override
           public void write(JsonWriter out, Contact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Contact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Contact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Contact
   * @throws IOException if the JSON string is invalid with respect to Contact
   */
  public static Contact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Contact.class);
  }

  /**
   * Convert an instance of Contact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

