/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ClickSend;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Account.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.AddAllowedEmail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.AddAllowedEmailRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.AgreeToRulesAndRegulation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.AlphaTag.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Attachment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.BuyNumberRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.BuyNumberRequestRegistrationData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailCampaignPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailCampaignPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailCampaignPriceDataData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailCampaignPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateEmailPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateFaxPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateFaxPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateFaxPriceRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateLetterPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateLetterPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateLetterPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsCampaignPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsCampaignPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsCampaignPriceDataData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateMmsPriceRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculatePostcardPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsCampaignPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsCampaignPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsCampaignPriceDataData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsCampaignPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceDataSummary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceDataSummaryCountriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceDataSummaryCountriesInnerCountry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateSmsPriceRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateVoicePrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateVoicePriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CalculateVoicePriceRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelAllSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelAllSmsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelAllSmsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelAllVoiceMessages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelEmailCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelEmailCampaignRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelMmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelScheduledLetter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelScheduledPostcard.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelSmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CancelVoiceMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Contact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ContactList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CopyContactToList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Country.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateAllowedEmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateAllowedEmailAddressRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDefaultSender.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDefaultSenderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDefaultSenderRequestDefaultSenderStrategiesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDeliveryIssue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDeliveryIssueData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateDeliveryIssueRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateEmailDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateEmailTemplateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateFaxDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateFaxDeliveryReceiptRuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateFaxInboundRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateFaxInboundRuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateListRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateNewContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateNewContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateResellerAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateResellerAccountData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateResellerAccountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateReturnAddressRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsDeliveryReceiptRuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsInboundAutomation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsInboundAutomationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSmsTemplateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateStrippedStringRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateStrippedStringRuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSubaccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateSubaccountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateTestInboundSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateTestInboundSmsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateTestSmsReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateTestSmsReceiptData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateTestSmsReceiptRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CreateVoiceDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Currency.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CurrentPaymentInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.CurrentPaymentInfoData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DefaultSender.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DefaultSenderDefaultSenderStrategiesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DefaultSenderError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DefaultSenderErrorDetailsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteAllowedEmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteEmailDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteFaxDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteFaxInboundRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteSmsDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteSmsInboundAutomation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteSmsTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteStrippedStringRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteSubaccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeleteVoiceDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DeliveryIssue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DetectAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.DetectAddressData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.EmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.EmailCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.EmailCampaignHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.EmailDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportEmailHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportLetterHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportMmsHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportPostcardHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportSmsHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportSmsHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ExportVoiceHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Fax.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.FaxDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.FaxReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ForgotPassword.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ForgotPasswordRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ForgotUsername.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ForgotUsernameRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GenerateNewApiKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GenerateNewApiKeyData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GenerateNewApiKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetAllDeliveryIssues.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetCountriesForGlobalSending.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetDefaultSenderDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetDefaultSendersList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetDefaultSendersListData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetSpecificContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetStatistics.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetStatisticsDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetStatisticsDataInnerDeviceInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetStatisticsDataInnerLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetTracking.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetTrackingDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetTrackingDataInnerContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetVoiceHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GetVoiceHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GlobalSending.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.GlobalSendingRegistrationStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ImportContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ImportContactsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ImportContactsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.InboundFaxRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.InboundSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.InboundSmsTest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListAlphaTags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCompliantSenderTypes200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCompliantSenderTypes200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCompliantSenderTypes200ResponseDataDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInnerAllowedSenderCountries.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCountries.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListCountriesDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListOwnNumbers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListOwnNumbersMetadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ListOwnNumbersMetadataPagination.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MarkInboundSmsAsRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MarkSmsReceiptAsRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MarkSmsReceiptAsReadRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MarkSpecificInboundSmsMessageAsRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MasterEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MasterEmailTemplateThumbnail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Mms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.MmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Model400Error.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.OwnNumber.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Pagination.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PostReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PostcardRecipient.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PostcardRecipientReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PurchaseDedicatedNumber.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PurchaseDedicatedNumberData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PurchaseRechargePackage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.PurchaseRechargePackageData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Recipient.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RegisterNumbers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RegisterNumbersRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RemoveDuplicateContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RemoveDuplicateContactsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RemoveDuplicateContactsRequestFields.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RemoveOptedOutContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RemoveOptedOutContactsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequestBusinessesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequestBusinessesInnerBusinessAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequestBusinessesInnerBusinessInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequestBusinessesInnerPartnerRepresentative.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestAlphaTagRequestBusinessesInnerRepresentative.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestOwnNumberVerificationOtp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.RequestOwnNumberVerificationOtpRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ResellerAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ResellerTransferCredit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SelectCountriesForGlobalSending.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SelectCountriesForGlobalSendingRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailCampaignData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailCampaignRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailRequestAttachmentsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailRequestFrom.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailRequestToInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailVerificationToken.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailVerificationTokenRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailVerificationTokenRequestFrom.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendEmailVerificationTokenRequestToInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendFax.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendFaxData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendFaxRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendFaxRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendLetter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendLetterData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendLetterRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMmsCampaignRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMmsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMmsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendMmsRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendPostcard.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendPostcardData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendPostcardRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendPostcardRequestRecipientsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSmsCampaignRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSmsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSmsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendSmsRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendVoiceMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendVoiceMessageData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendVoiceMessageRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendVoiceMessageRequestMessagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SendersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Sms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsCampaignSendersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsInboundRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsSendSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.SmsTemplateUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Subaccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.Timezones.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.TransactionalEmail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.TransferContactToList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateClientAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateDefaultSender.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateDefaultSenderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateEmailCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateEmailCampaignRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateEmailDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateEmailTemplateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateFaxDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateFaxDeliveryReceiptRuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateFaxInboundRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateMmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdatePaymentInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdatePaymentInfoData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdatePaymentInfoRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateReturnAddressRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSmsDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSmsInboundAutomation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSmsInboundAutomationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSmsTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateStrippedStringRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSubaccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateSubaccountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UpdateVoiceDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.UserEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VerifyAllowedEmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VerifyAllowedEmailAddressRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VerifyOwnNumberOtp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VerifyOwnNumberOtpRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewASpecificInboundSmsMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewASpecificSmsTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewASpecificSmsTemplateData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountUsage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountUsageData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountUsageDataEmailInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountUsageDataSmsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAccountUsageDataSmsTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllEmailCampaigns.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllEmailCampaignsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllMmsCampaigns.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllMmsCampaignsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllTransactions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllTransactionsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllTransactionsDataAllOfDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllowedEmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllowedEmailAddresses.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllowedEmailAddressesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllowedEmails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAllowedEmailsDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAvailableNumbers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewAvailableNumbersDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewClientAccounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewClientAccountsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewCountries.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailCampaignHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailCampaignHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailDeliveryReceiptRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailDeliveryReceiptRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailTemplates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailTemplatesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewEmailTemplatesDataDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxDeliveryReceiptRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxDeliveryReceiptRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxInboundRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxInboundRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxInboundRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxReceipts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewFaxReceiptsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewInboundSms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewInboundSmsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewLetterHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewLetterHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewListContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewLists.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewListsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMasterEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMasterEmailTemplates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMmsHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMmsHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewMmsHistoryDataAllOfDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewPostcardHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewPostcardHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewRechargePackages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewRechargePackagesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewRechargePackagesDataPackagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewReferralAccounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewReferralAccountsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewReferralAccountsDataAllOfDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsCampaigns.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsCampaignsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsDeliveryReceiptRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsDeliveryReceiptRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsHistoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsHistoryDataAllOfDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsInboundAutomation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsInboundAutomations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsInboundAutomationsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsReceipts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsReceiptsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsStatistics.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsStatisticsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsStatisticsDataStatInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsStatisticsDataTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsTemplates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSmsTemplatesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificClientAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificFaxReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificReturnAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificSmsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificSmsReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificSubaccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSpecificTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewStrippedStringRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewStrippedStringRuleData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewStrippedStringRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewStrippedStringRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewStrippedStringRulesDataDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewSubaccounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewTemplateCategories.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewTemplateCategoriesDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewTemplateCategory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewTemplateCategoryData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewTemplatesInCategory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceDeliveryReceiptRules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceDeliveryReceiptRulesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceLanguages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceLanguagesDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceReceipts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceReceiptsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatistics.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatisticsData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatisticsDataStatsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatisticsDataStatsInnerOutbound.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatisticsDataTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewVoiceStatisticsDataTotalOutbound.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourNumbers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourNumbersData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourNumbersDataAllOfDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourNumbersDataAllOfDataInnerStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourReturnAddresses.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.ViewYourReturnAddressesData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VoiceDeliveryReceiptRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VoiceMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ClickSend.Model.VoiceReceipt.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
