/*
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contact list import model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ContactListImport {
  public static final String SERIALIZED_NAME_FILE_URL = "file_url";
  @SerializedName(SERIALIZED_NAME_FILE_URL)
  @javax.annotation.Nonnull
  private String fileUrl;

  public static final String SERIALIZED_NAME_FIELD_ORDER = "field_order";
  @SerializedName(SERIALIZED_NAME_FIELD_ORDER)
  @javax.annotation.Nonnull
  private List<String> fieldOrder = new ArrayList<>();

  public ContactListImport() {
    this.classType = this.getClass().getSimpleName();
  }

  public ContactListImport fileUrl(@javax.annotation.Nonnull String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

  /**
   * URL of file to process
   * @return fileUrl
   */
  @javax.annotation.Nonnull
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(@javax.annotation.Nonnull String fileUrl) {
    this.fileUrl = fileUrl;
  }


  public ContactListImport fieldOrder(@javax.annotation.Nonnull List<String> fieldOrder) {
    this.fieldOrder = fieldOrder;
    return this;
  }

  public ContactListImport addFieldOrderItem(String fieldOrderItem) {
    if (this.fieldOrder == null) {
      this.fieldOrder = new ArrayList<>();
    }
    this.fieldOrder.add(fieldOrderItem);
    return this;
  }

  /**
   * Order of fields in file
   * @return fieldOrder
   */
  @javax.annotation.Nonnull
  public List<String> getFieldOrder() {
    return fieldOrder;
  }

  public void setFieldOrder(@javax.annotation.Nonnull List<String> fieldOrder) {
    this.fieldOrder = fieldOrder;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactListImport contactListImport = (ContactListImport) o;
    return Objects.equals(this.fileUrl, contactListImport.fileUrl) &&
        Objects.equals(this.fieldOrder, contactListImport.fieldOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileUrl, fieldOrder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactListImport {\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    fieldOrder: ").append(toIndentedString(fieldOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("file_url", "field_order"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("file_url", "field_order"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContactListImport
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContactListImport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ContactListImport is not found in the empty JSON string", ContactListImport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContactListImport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ContactListImport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ContactListImport.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContactListImport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContactListImport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContactListImport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContactListImport.class));

       return (TypeAdapter<T>) new TypeAdapter<ContactListImport>() {
           @Override
           public void write(JsonWriter out, ContactListImport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContactListImport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContactListImport given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContactListImport
   * @throws IOException if the JSON string is invalid with respect to ContactListImport
   */
  public static ContactListImport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContactListImport.class);
  }

  /**
   * Convert an instance of ContactListImport to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

