/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * EmailCampaignHistory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class EmailCampaignHistory {
  public static final String SERIALIZED_NAME_EMAIL_CAMPAIGN_ID = "email_campaign_id";
  @SerializedName(SERIALIZED_NAME_EMAIL_CAMPAIGN_ID)
  @javax.annotation.Nullable
  private Integer emailCampaignId;

  public static final String SERIALIZED_NAME_FROM_NAME = "from_name";
  @SerializedName(SERIALIZED_NAME_FROM_NAME)
  @javax.annotation.Nullable
  private String fromName;

  public static final String SERIALIZED_NAME_FROM_ADDRESS = "from_address";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS)
  @javax.annotation.Nullable
  private String fromAddress;

  public static final String SERIALIZED_NAME_TO_NAME = "to_name";
  @SerializedName(SERIALIZED_NAME_TO_NAME)
  @javax.annotation.Nullable
  private String toName;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "to_address";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  @javax.annotation.Nullable
  private String toAddress;

  public static final String SERIALIZED_NAME_CONTACT_ID = "contact_id";
  @SerializedName(SERIALIZED_NAME_CONTACT_ID)
  @javax.annotation.Nullable
  private Integer contactId;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nullable
  private String subject;

  public static final String SERIALIZED_NAME_MESSAGE_ID = "message_id";
  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  @javax.annotation.Nullable
  private String messageId;

  public static final String SERIALIZED_NAME_PROCESSED_AT = "processed_at";
  @SerializedName(SERIALIZED_NAME_PROCESSED_AT)
  @javax.annotation.Nullable
  private String processedAt;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_OPEN_COUNT = "open_count";
  @SerializedName(SERIALIZED_NAME_OPEN_COUNT)
  @javax.annotation.Nullable
  private Integer openCount;

  public static final String SERIALIZED_NAME_CLICK_COUNT = "click_count";
  @SerializedName(SERIALIZED_NAME_CLICK_COUNT)
  @javax.annotation.Nullable
  private Integer clickCount;

  public static final String SERIALIZED_NAME_HARD_BOUNCE_COUNT = "hard_bounce_count";
  @SerializedName(SERIALIZED_NAME_HARD_BOUNCE_COUNT)
  @javax.annotation.Nullable
  private Integer hardBounceCount;

  public static final String SERIALIZED_NAME_SOFT_BOUNCE_COUNT = "soft_bounce_count";
  @SerializedName(SERIALIZED_NAME_SOFT_BOUNCE_COUNT)
  @javax.annotation.Nullable
  private Integer softBounceCount;

  public EmailCampaignHistory() {
  }

  public EmailCampaignHistory emailCampaignId(@javax.annotation.Nullable Integer emailCampaignId) {
    this.emailCampaignId = emailCampaignId;
    return this;
  }

  /**
   * The ID of the email campaign.
   * @return emailCampaignId
   */
  @javax.annotation.Nullable
  public Integer getEmailCampaignId() {
    return emailCampaignId;
  }

  public void setEmailCampaignId(@javax.annotation.Nullable Integer emailCampaignId) {
    this.emailCampaignId = emailCampaignId;
  }


  public EmailCampaignHistory fromName(@javax.annotation.Nullable String fromName) {
    this.fromName = fromName;
    return this;
  }

  /**
   * The name of the sender.
   * @return fromName
   */
  @javax.annotation.Nullable
  public String getFromName() {
    return fromName;
  }

  public void setFromName(@javax.annotation.Nullable String fromName) {
    this.fromName = fromName;
  }


  public EmailCampaignHistory fromAddress(@javax.annotation.Nullable String fromAddress) {
    this.fromAddress = fromAddress;
    return this;
  }

  /**
   * The email address of the sender.
   * @return fromAddress
   */
  @javax.annotation.Nullable
  public String getFromAddress() {
    return fromAddress;
  }

  public void setFromAddress(@javax.annotation.Nullable String fromAddress) {
    this.fromAddress = fromAddress;
  }


  public EmailCampaignHistory toName(@javax.annotation.Nullable String toName) {
    this.toName = toName;
    return this;
  }

  /**
   * The name of the recipient.
   * @return toName
   */
  @javax.annotation.Nullable
  public String getToName() {
    return toName;
  }

  public void setToName(@javax.annotation.Nullable String toName) {
    this.toName = toName;
  }


  public EmailCampaignHistory toAddress(@javax.annotation.Nullable String toAddress) {
    this.toAddress = toAddress;
    return this;
  }

  /**
   * The email address of the recipient.
   * @return toAddress
   */
  @javax.annotation.Nullable
  public String getToAddress() {
    return toAddress;
  }

  public void setToAddress(@javax.annotation.Nullable String toAddress) {
    this.toAddress = toAddress;
  }


  public EmailCampaignHistory contactId(@javax.annotation.Nullable Integer contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * The ID of the contact associated with the email.
   * @return contactId
   */
  @javax.annotation.Nullable
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(@javax.annotation.Nullable Integer contactId) {
    this.contactId = contactId;
  }


  public EmailCampaignHistory subject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * The subject of the email.
   * @return subject
   */
  @javax.annotation.Nullable
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public EmailCampaignHistory messageId(@javax.annotation.Nullable String messageId) {
    this.messageId = messageId;
    return this;
  }

  /**
   * The unique ID of the email message.
   * @return messageId
   */
  @javax.annotation.Nullable
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(@javax.annotation.Nullable String messageId) {
    this.messageId = messageId;
  }


  public EmailCampaignHistory processedAt(@javax.annotation.Nullable String processedAt) {
    this.processedAt = processedAt;
    return this;
  }

  /**
   * The date and time when the email was processed.
   * @return processedAt
   */
  @javax.annotation.Nullable
  public String getProcessedAt() {
    return processedAt;
  }

  public void setProcessedAt(@javax.annotation.Nullable String processedAt) {
    this.processedAt = processedAt;
  }


  public EmailCampaignHistory status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the email (e.g., SpamReport, Sent).
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public EmailCampaignHistory openCount(@javax.annotation.Nullable Integer openCount) {
    this.openCount = openCount;
    return this;
  }

  /**
   * The count of times the email was opened.
   * @return openCount
   */
  @javax.annotation.Nullable
  public Integer getOpenCount() {
    return openCount;
  }

  public void setOpenCount(@javax.annotation.Nullable Integer openCount) {
    this.openCount = openCount;
  }


  public EmailCampaignHistory clickCount(@javax.annotation.Nullable Integer clickCount) {
    this.clickCount = clickCount;
    return this;
  }

  /**
   * The count of times links in the email were clicked.
   * @return clickCount
   */
  @javax.annotation.Nullable
  public Integer getClickCount() {
    return clickCount;
  }

  public void setClickCount(@javax.annotation.Nullable Integer clickCount) {
    this.clickCount = clickCount;
  }


  public EmailCampaignHistory hardBounceCount(@javax.annotation.Nullable Integer hardBounceCount) {
    this.hardBounceCount = hardBounceCount;
    return this;
  }

  /**
   * The count of hard bounces for the email.
   * @return hardBounceCount
   */
  @javax.annotation.Nullable
  public Integer getHardBounceCount() {
    return hardBounceCount;
  }

  public void setHardBounceCount(@javax.annotation.Nullable Integer hardBounceCount) {
    this.hardBounceCount = hardBounceCount;
  }


  public EmailCampaignHistory softBounceCount(@javax.annotation.Nullable Integer softBounceCount) {
    this.softBounceCount = softBounceCount;
    return this;
  }

  /**
   * The count of soft bounces for the email.
   * @return softBounceCount
   */
  @javax.annotation.Nullable
  public Integer getSoftBounceCount() {
    return softBounceCount;
  }

  public void setSoftBounceCount(@javax.annotation.Nullable Integer softBounceCount) {
    this.softBounceCount = softBounceCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailCampaignHistory emailCampaignHistory = (EmailCampaignHistory) o;
    return Objects.equals(this.emailCampaignId, emailCampaignHistory.emailCampaignId) &&
        Objects.equals(this.fromName, emailCampaignHistory.fromName) &&
        Objects.equals(this.fromAddress, emailCampaignHistory.fromAddress) &&
        Objects.equals(this.toName, emailCampaignHistory.toName) &&
        Objects.equals(this.toAddress, emailCampaignHistory.toAddress) &&
        Objects.equals(this.contactId, emailCampaignHistory.contactId) &&
        Objects.equals(this.subject, emailCampaignHistory.subject) &&
        Objects.equals(this.messageId, emailCampaignHistory.messageId) &&
        Objects.equals(this.processedAt, emailCampaignHistory.processedAt) &&
        Objects.equals(this.status, emailCampaignHistory.status) &&
        Objects.equals(this.openCount, emailCampaignHistory.openCount) &&
        Objects.equals(this.clickCount, emailCampaignHistory.clickCount) &&
        Objects.equals(this.hardBounceCount, emailCampaignHistory.hardBounceCount) &&
        Objects.equals(this.softBounceCount, emailCampaignHistory.softBounceCount);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailCampaignId, fromName, fromAddress, toName, toAddress, contactId, subject, messageId, processedAt, status, openCount, clickCount, hardBounceCount, softBounceCount);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailCampaignHistory {\n");
    sb.append("    emailCampaignId: ").append(toIndentedString(emailCampaignId)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    toName: ").append(toIndentedString(toName)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    processedAt: ").append(toIndentedString(processedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    openCount: ").append(toIndentedString(openCount)).append("\n");
    sb.append("    clickCount: ").append(toIndentedString(clickCount)).append("\n");
    sb.append("    hardBounceCount: ").append(toIndentedString(hardBounceCount)).append("\n");
    sb.append("    softBounceCount: ").append(toIndentedString(softBounceCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("email_campaign_id", "from_name", "from_address", "to_name", "to_address", "contact_id", "subject", "message_id", "processed_at", "status", "open_count", "click_count", "hard_bounce_count", "soft_bounce_count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EmailCampaignHistory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmailCampaignHistory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EmailCampaignHistory is not found in the empty JSON string", EmailCampaignHistory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EmailCampaignHistory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EmailCampaignHistory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("from_name") != null && !jsonObj.get("from_name").isJsonNull()) && !jsonObj.get("from_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_name").toString()));
      }
      if ((jsonObj.get("from_address") != null && !jsonObj.get("from_address").isJsonNull()) && !jsonObj.get("from_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_address").toString()));
      }
      if ((jsonObj.get("to_name") != null && !jsonObj.get("to_name").isJsonNull()) && !jsonObj.get("to_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `to_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_name").toString()));
      }
      if ((jsonObj.get("to_address") != null && !jsonObj.get("to_address").isJsonNull()) && !jsonObj.get("to_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `to_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_address").toString()));
      }
      if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("message_id") != null && !jsonObj.get("message_id").isJsonNull()) && !jsonObj.get("message_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_id").toString()));
      }
      if ((jsonObj.get("processed_at") != null && !jsonObj.get("processed_at").isJsonNull()) && !jsonObj.get("processed_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `processed_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("processed_at").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmailCampaignHistory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmailCampaignHistory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmailCampaignHistory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmailCampaignHistory.class));

       return (TypeAdapter<T>) new TypeAdapter<EmailCampaignHistory>() {
           @Override
           public void write(JsonWriter out, EmailCampaignHistory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmailCampaignHistory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EmailCampaignHistory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EmailCampaignHistory
   * @throws IOException if the JSON string is invalid with respect to EmailCampaignHistory
   */
  public static EmailCampaignHistory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmailCampaignHistory.class);
  }

  /**
   * Convert an instance of EmailCampaignHistory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

