/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FaxReceipt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class FaxReceipt {
  public static final String SERIALIZED_NAME_TIMESTAMP_SEND = "timestamp_send";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_SEND)
  @javax.annotation.Nullable
  private String timestampSend;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nullable
  private String timestamp;

  public static final String SERIALIZED_NAME_MESSAGE_ID = "message_id";
  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  @javax.annotation.Nullable
  private String messageId;

  public static final String SERIALIZED_NAME_STATUS_CODE = "status_code";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  @javax.annotation.Nullable
  private String statusCode;

  public static final String SERIALIZED_NAME_STATUS_TEXT = "status_text";
  @SerializedName(SERIALIZED_NAME_STATUS_TEXT)
  @javax.annotation.Nullable
  private String statusText;

  public static final String SERIALIZED_NAME_ERROR_CODE = "error_code";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  @javax.annotation.Nullable
  private String errorCode;

  public static final String SERIALIZED_NAME_ERROR_TEXT = "error_text";
  @SerializedName(SERIALIZED_NAME_ERROR_TEXT)
  @javax.annotation.Nullable
  private String errorText;

  public static final String SERIALIZED_NAME_CUSTOM_STRING = "custom_string";
  @SerializedName(SERIALIZED_NAME_CUSTOM_STRING)
  @javax.annotation.Nullable
  private String customString;

  public static final String SERIALIZED_NAME_SUBACCOUNT_ID = "subaccount_id";
  @SerializedName(SERIALIZED_NAME_SUBACCOUNT_ID)
  @javax.annotation.Nullable
  private Integer subaccountId;

  public static final String SERIALIZED_NAME_MESSAGE_TYPE = "message_type";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TYPE)
  @javax.annotation.Nullable
  private String messageType;

  public FaxReceipt() {
  }

  public FaxReceipt timestampSend(@javax.annotation.Nullable String timestampSend) {
    this.timestampSend = timestampSend;
    return this;
  }

  /**
   * The timestamp when the message was sent.
   * @return timestampSend
   */
  @javax.annotation.Nullable
  public String getTimestampSend() {
    return timestampSend;
  }

  public void setTimestampSend(@javax.annotation.Nullable String timestampSend) {
    this.timestampSend = timestampSend;
  }


  public FaxReceipt timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The timestamp associated with the message.
   * @return timestamp
   */
  @javax.annotation.Nullable
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public FaxReceipt messageId(@javax.annotation.Nullable String messageId) {
    this.messageId = messageId;
    return this;
  }

  /**
   * The ID of the message.
   * @return messageId
   */
  @javax.annotation.Nullable
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(@javax.annotation.Nullable String messageId) {
    this.messageId = messageId;
  }


  public FaxReceipt statusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * The status code of the message.
   * @return statusCode
   */
  @javax.annotation.Nullable
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(@javax.annotation.Nullable String statusCode) {
    this.statusCode = statusCode;
  }


  public FaxReceipt statusText(@javax.annotation.Nullable String statusText) {
    this.statusText = statusText;
    return this;
  }

  /**
   * The status text of the message.
   * @return statusText
   */
  @javax.annotation.Nullable
  public String getStatusText() {
    return statusText;
  }

  public void setStatusText(@javax.annotation.Nullable String statusText) {
    this.statusText = statusText;
  }


  public FaxReceipt errorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * The error code associated with the message.
   * @return errorCode
   */
  @javax.annotation.Nullable
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }


  public FaxReceipt errorText(@javax.annotation.Nullable String errorText) {
    this.errorText = errorText;
    return this;
  }

  /**
   * The error text associated with the message.
   * @return errorText
   */
  @javax.annotation.Nullable
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(@javax.annotation.Nullable String errorText) {
    this.errorText = errorText;
  }


  public FaxReceipt customString(@javax.annotation.Nullable String customString) {
    this.customString = customString;
    return this;
  }

  /**
   * A custom string associated with the message.
   * @return customString
   */
  @javax.annotation.Nullable
  public String getCustomString() {
    return customString;
  }

  public void setCustomString(@javax.annotation.Nullable String customString) {
    this.customString = customString;
  }


  public FaxReceipt subaccountId(@javax.annotation.Nullable Integer subaccountId) {
    this.subaccountId = subaccountId;
    return this;
  }

  /**
   * The ID of the subaccount.
   * @return subaccountId
   */
  @javax.annotation.Nullable
  public Integer getSubaccountId() {
    return subaccountId;
  }

  public void setSubaccountId(@javax.annotation.Nullable Integer subaccountId) {
    this.subaccountId = subaccountId;
  }


  public FaxReceipt messageType(@javax.annotation.Nullable String messageType) {
    this.messageType = messageType;
    return this;
  }

  /**
   * The type of message.
   * @return messageType
   */
  @javax.annotation.Nullable
  public String getMessageType() {
    return messageType;
  }

  public void setMessageType(@javax.annotation.Nullable String messageType) {
    this.messageType = messageType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaxReceipt faxReceipt = (FaxReceipt) o;
    return Objects.equals(this.timestampSend, faxReceipt.timestampSend) &&
        Objects.equals(this.timestamp, faxReceipt.timestamp) &&
        Objects.equals(this.messageId, faxReceipt.messageId) &&
        Objects.equals(this.statusCode, faxReceipt.statusCode) &&
        Objects.equals(this.statusText, faxReceipt.statusText) &&
        Objects.equals(this.errorCode, faxReceipt.errorCode) &&
        Objects.equals(this.errorText, faxReceipt.errorText) &&
        Objects.equals(this.customString, faxReceipt.customString) &&
        Objects.equals(this.subaccountId, faxReceipt.subaccountId) &&
        Objects.equals(this.messageType, faxReceipt.messageType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestampSend, timestamp, messageId, statusCode, statusText, errorCode, errorText, customString, subaccountId, messageType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaxReceipt {\n");
    sb.append("    timestampSend: ").append(toIndentedString(timestampSend)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusText: ").append(toIndentedString(statusText)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    customString: ").append(toIndentedString(customString)).append("\n");
    sb.append("    subaccountId: ").append(toIndentedString(subaccountId)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("timestamp_send", "timestamp", "message_id", "status_code", "status_text", "error_code", "error_text", "custom_string", "subaccount_id", "message_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FaxReceipt
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FaxReceipt.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FaxReceipt is not found in the empty JSON string", FaxReceipt.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FaxReceipt.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FaxReceipt` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("timestamp_send") != null && !jsonObj.get("timestamp_send").isJsonNull()) && !jsonObj.get("timestamp_send").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timestamp_send` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_send").toString()));
      }
      if ((jsonObj.get("timestamp") != null && !jsonObj.get("timestamp").isJsonNull()) && !jsonObj.get("timestamp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timestamp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp").toString()));
      }
      if ((jsonObj.get("message_id") != null && !jsonObj.get("message_id").isJsonNull()) && !jsonObj.get("message_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_id").toString()));
      }
      if ((jsonObj.get("status_code") != null && !jsonObj.get("status_code").isJsonNull()) && !jsonObj.get("status_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status_code").toString()));
      }
      if ((jsonObj.get("status_text") != null && !jsonObj.get("status_text").isJsonNull()) && !jsonObj.get("status_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status_text").toString()));
      }
      if ((jsonObj.get("error_code") != null && !jsonObj.get("error_code").isJsonNull()) && !jsonObj.get("error_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_code").toString()));
      }
      if ((jsonObj.get("error_text") != null && !jsonObj.get("error_text").isJsonNull()) && !jsonObj.get("error_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_text").toString()));
      }
      if ((jsonObj.get("custom_string") != null && !jsonObj.get("custom_string").isJsonNull()) && !jsonObj.get("custom_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custom_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_string").toString()));
      }
      if ((jsonObj.get("message_type") != null && !jsonObj.get("message_type").isJsonNull()) && !jsonObj.get("message_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FaxReceipt.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FaxReceipt' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FaxReceipt> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FaxReceipt.class));

       return (TypeAdapter<T>) new TypeAdapter<FaxReceipt>() {
           @Override
           public void write(JsonWriter out, FaxReceipt value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FaxReceipt read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FaxReceipt given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FaxReceipt
   * @throws IOException if the JSON string is invalid with respect to FaxReceipt
   */
  public static FaxReceipt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FaxReceipt.class);
  }

  /**
   * Convert an instance of FaxReceipt to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

