/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RegisterNumbersRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class RegisterNumbersRequest {
  public static final String SERIALIZED_NAME_FULL_NAME = "full_name";
  @SerializedName(SERIALIZED_NAME_FULL_NAME)
  @javax.annotation.Nonnull
  private String fullName;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "company_name";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  @javax.annotation.Nonnull
  private String companyName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_WEBSITE_URL = "website_url";
  @SerializedName(SERIALIZED_NAME_WEBSITE_URL)
  @javax.annotation.Nonnull
  private String websiteUrl;

  public static final String SERIALIZED_NAME_SAMPLE_MESSAGE = "sample_message";
  @SerializedName(SERIALIZED_NAME_SAMPLE_MESSAGE)
  @javax.annotation.Nonnull
  private String sampleMessage;

  public static final String SERIALIZED_NAME_PRIMARY_USE_CASE = "primary_use_case";
  @SerializedName(SERIALIZED_NAME_PRIMARY_USE_CASE)
  @javax.annotation.Nonnull
  private String primaryUseCase;

  public static final String SERIALIZED_NAME_COMPANY_NUMBER = "company_number";
  @SerializedName(SERIALIZED_NAME_COMPANY_NUMBER)
  @javax.annotation.Nonnull
  private String companyNumber;

  public static final String SERIALIZED_NAME_AREA_CODE = "area_code";
  @SerializedName(SERIALIZED_NAME_AREA_CODE)
  @javax.annotation.Nonnull
  private String areaCode;

  public RegisterNumbersRequest() {
  }

  public RegisterNumbersRequest fullName(@javax.annotation.Nonnull String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Legal full name of the individual registering the number. Must be a personal name, not a business name.
   * @return fullName
   */
  @javax.annotation.Nonnull
  public String getFullName() {
    return fullName;
  }

  public void setFullName(@javax.annotation.Nonnull String fullName) {
    this.fullName = fullName;
  }


  public RegisterNumbersRequest companyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Legal business name of the organization requesting registration
   * @return companyName
   */
  @javax.annotation.Nonnull
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
  }


  public RegisterNumbersRequest email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Contact email address for registration communications and notifications
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public RegisterNumbersRequest websiteUrl(@javax.annotation.Nonnull String websiteUrl) {
    this.websiteUrl = websiteUrl;
    return this;
  }

  /**
   * Official business website URL
   * @return websiteUrl
   */
  @javax.annotation.Nonnull
  public String getWebsiteUrl() {
    return websiteUrl;
  }

  public void setWebsiteUrl(@javax.annotation.Nonnull String websiteUrl) {
    this.websiteUrl = websiteUrl;
  }


  public RegisterNumbersRequest sampleMessage(@javax.annotation.Nonnull String sampleMessage) {
    this.sampleMessage = sampleMessage;
    return this;
  }

  /**
   * Representative example of messages that will be sent using this number
   * @return sampleMessage
   */
  @javax.annotation.Nonnull
  public String getSampleMessage() {
    return sampleMessage;
  }

  public void setSampleMessage(@javax.annotation.Nonnull String sampleMessage) {
    this.sampleMessage = sampleMessage;
  }


  public RegisterNumbersRequest primaryUseCase(@javax.annotation.Nonnull String primaryUseCase) {
    this.primaryUseCase = primaryUseCase;
    return this;
  }

  /**
   * Primary intended purpose for the registered number (e.g., Marketing, Notifications, Authentication)
   * @return primaryUseCase
   */
  @javax.annotation.Nonnull
  public String getPrimaryUseCase() {
    return primaryUseCase;
  }

  public void setPrimaryUseCase(@javax.annotation.Nonnull String primaryUseCase) {
    this.primaryUseCase = primaryUseCase;
  }


  public RegisterNumbersRequest companyNumber(@javax.annotation.Nonnull String companyNumber) {
    this.companyNumber = companyNumber;
    return this;
  }

  /**
   * Official support phone number of the organization requesting registration
   * @return companyNumber
   */
  @javax.annotation.Nonnull
  public String getCompanyNumber() {
    return companyNumber;
  }

  public void setCompanyNumber(@javax.annotation.Nonnull String companyNumber) {
    this.companyNumber = companyNumber;
  }


  public RegisterNumbersRequest areaCode(@javax.annotation.Nonnull String areaCode) {
    this.areaCode = areaCode;
    return this;
  }

  /**
   * Your area codes, please provide your top 3 area codes in case your 1st choice is not available
   * @return areaCode
   */
  @javax.annotation.Nonnull
  public String getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(@javax.annotation.Nonnull String areaCode) {
    this.areaCode = areaCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterNumbersRequest registerNumbersRequest = (RegisterNumbersRequest) o;
    return Objects.equals(this.fullName, registerNumbersRequest.fullName) &&
        Objects.equals(this.companyName, registerNumbersRequest.companyName) &&
        Objects.equals(this.email, registerNumbersRequest.email) &&
        Objects.equals(this.websiteUrl, registerNumbersRequest.websiteUrl) &&
        Objects.equals(this.sampleMessage, registerNumbersRequest.sampleMessage) &&
        Objects.equals(this.primaryUseCase, registerNumbersRequest.primaryUseCase) &&
        Objects.equals(this.companyNumber, registerNumbersRequest.companyNumber) &&
        Objects.equals(this.areaCode, registerNumbersRequest.areaCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, companyName, email, websiteUrl, sampleMessage, primaryUseCase, companyNumber, areaCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterNumbersRequest {\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    websiteUrl: ").append(toIndentedString(websiteUrl)).append("\n");
    sb.append("    sampleMessage: ").append(toIndentedString(sampleMessage)).append("\n");
    sb.append("    primaryUseCase: ").append(toIndentedString(primaryUseCase)).append("\n");
    sb.append("    companyNumber: ").append(toIndentedString(companyNumber)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("full_name", "company_name", "email", "website_url", "sample_message", "primary_use_case", "company_number", "area_code"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("full_name", "company_name", "email", "website_url", "sample_message", "primary_use_case", "company_number", "area_code"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RegisterNumbersRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RegisterNumbersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RegisterNumbersRequest is not found in the empty JSON string", RegisterNumbersRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RegisterNumbersRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RegisterNumbersRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RegisterNumbersRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("full_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `full_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("full_name").toString()));
      }
      if (!jsonObj.get("company_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `company_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company_name").toString()));
      }
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (!jsonObj.get("website_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `website_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("website_url").toString()));
      }
      if (!jsonObj.get("sample_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sample_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sample_message").toString()));
      }
      if (!jsonObj.get("primary_use_case").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `primary_use_case` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primary_use_case").toString()));
      }
      if (!jsonObj.get("company_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `company_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company_number").toString()));
      }
      if (!jsonObj.get("area_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `area_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("area_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RegisterNumbersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RegisterNumbersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RegisterNumbersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RegisterNumbersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RegisterNumbersRequest>() {
           @Override
           public void write(JsonWriter out, RegisterNumbersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RegisterNumbersRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RegisterNumbersRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RegisterNumbersRequest
   * @throws IOException if the JSON string is invalid with respect to RegisterNumbersRequest
   */
  public static RegisterNumbersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RegisterNumbersRequest.class);
  }

  /**
   * Convert an instance of RegisterNumbersRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

