/*
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.VoiceMessage;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SendVoiceMessageData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class SendVoiceMessageData {
  public static final String SERIALIZED_NAME_TOTAL_PRICE = "total_price";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  @javax.annotation.Nullable
  private BigDecimal totalPrice;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  @javax.annotation.Nullable
  private BigDecimal totalCount;

  public static final String SERIALIZED_NAME_QUEUED_COUNT = "queued_count";
  @SerializedName(SERIALIZED_NAME_QUEUED_COUNT)
  @javax.annotation.Nullable
  private BigDecimal queuedCount;

  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  @javax.annotation.Nullable
  private List<VoiceMessage> messages = new ArrayList<>();

  public static final String SERIALIZED_NAME_CURRENCY = "_currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private Currency currency;

  public SendVoiceMessageData() {
  }

  public SendVoiceMessageData totalPrice(@javax.annotation.Nullable BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

  /**
   * The total price of the message.
   * @return totalPrice
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(@javax.annotation.Nullable BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }


  public SendVoiceMessageData totalCount(@javax.annotation.Nullable BigDecimal totalCount) {
    this.totalCount = totalCount;
    return this;
  }

  /**
   * The total count of the message.
   * @return totalCount
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(@javax.annotation.Nullable BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  public SendVoiceMessageData queuedCount(@javax.annotation.Nullable BigDecimal queuedCount) {
    this.queuedCount = queuedCount;
    return this;
  }

  /**
   * The count of the queued message.
   * @return queuedCount
   */
  @javax.annotation.Nullable
  public BigDecimal getQueuedCount() {
    return queuedCount;
  }

  public void setQueuedCount(@javax.annotation.Nullable BigDecimal queuedCount) {
    this.queuedCount = queuedCount;
  }


  public SendVoiceMessageData messages(@javax.annotation.Nullable List<VoiceMessage> messages) {
    this.messages = messages;
    return this;
  }

  public SendVoiceMessageData addMessagesItem(VoiceMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nullable
  public List<VoiceMessage> getMessages() {
    return messages;
  }

  public void setMessages(@javax.annotation.Nullable List<VoiceMessage> messages) {
    this.messages = messages;
  }


  public SendVoiceMessageData currency(@javax.annotation.Nullable Currency currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public Currency getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable Currency currency) {
    this.currency = currency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendVoiceMessageData sendVoiceMessageData = (SendVoiceMessageData) o;
    return Objects.equals(this.totalPrice, sendVoiceMessageData.totalPrice) &&
        Objects.equals(this.totalCount, sendVoiceMessageData.totalCount) &&
        Objects.equals(this.queuedCount, sendVoiceMessageData.queuedCount) &&
        Objects.equals(this.messages, sendVoiceMessageData.messages) &&
        Objects.equals(this.currency, sendVoiceMessageData.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPrice, totalCount, queuedCount, messages, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendVoiceMessageData {\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    queuedCount: ").append(toIndentedString(queuedCount)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("total_price", "total_count", "queued_count", "messages", "_currency"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SendVoiceMessageData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SendVoiceMessageData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SendVoiceMessageData is not found in the empty JSON string", SendVoiceMessageData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SendVoiceMessageData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SendVoiceMessageData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("messages") != null && !jsonObj.get("messages").isJsonNull()) {
        JsonArray jsonArraymessages = jsonObj.getAsJsonArray("messages");
        if (jsonArraymessages != null) {
          // ensure the json data is an array
          if (!jsonObj.get("messages").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `messages` to be an array in the JSON string but got `%s`", jsonObj.get("messages").toString()));
          }

          // validate the optional field `messages` (array)
          for (int i = 0; i < jsonArraymessages.size(); i++) {
            VoiceMessage.validateJsonElement(jsonArraymessages.get(i));
          };
        }
      }
      // validate the optional field `_currency`
      if (jsonObj.get("_currency") != null && !jsonObj.get("_currency").isJsonNull()) {
        Currency.validateJsonElement(jsonObj.get("_currency"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SendVoiceMessageData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SendVoiceMessageData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SendVoiceMessageData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SendVoiceMessageData.class));

       return (TypeAdapter<T>) new TypeAdapter<SendVoiceMessageData>() {
           @Override
           public void write(JsonWriter out, SendVoiceMessageData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SendVoiceMessageData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SendVoiceMessageData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SendVoiceMessageData
   * @throws IOException if the JSON string is invalid with respect to SendVoiceMessageData
   */
  public static SendVoiceMessageData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SendVoiceMessageData.class);
  }

  /**
   * Convert an instance of SendVoiceMessageData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

